

server:
  port: 8079
  
spring:
 application:
  name: SECURITY-SERVICE
  
 datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security_service
    username: root
    password: root
 jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    
eureka:
 instance:
  prefer-ip-address: true
 client:
  register-with-eureka: true
  fetch-registry: true
  service-url:
   defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}

